routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


//Users

use App\Http\Controllers\BooksController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\AuthorsController;
use App\Http\Controllers\PublishersController;


//Dashboard
use App\Http\Controllers\BookController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AuthorController;
use App\Http\Controllers\PublisherController;



use App\Http\Controllers\CategoryController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('books', BooksController::class);
Route::resource('categories', CategoriesController::class);
Route::resource('authors', AuthorsController::class);
Route::resource('publishers', PublishersController::class);

Route::group(['middleware' => ['auth']], function () {

    Route::prefix('dashboard')->group(function () {
        //admin pages

        Route::get('/', [App\Http\Controllers\DashboardController::class, 'index'])->name('Dashboard');
        Route::get('book/{title}', ['as' => 'book.show', 'uses' =>   'BookController@show']);
        Route::resource('book', BookController::class);
        Route::resource('author', AuthorController::class);
        Route::resource('publisher', PublisherController::class);

        Route::resource('roles', RoleController::class);
        Route::resource('category', CategoryController::class);
        Route::resource('users', UserController::class);
    });
});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'author_id',
        'publisher_id',
        'category_id',
        'date_of_issue',
        'description',
        'cover',
    ];

    public function categories()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function publishers()
    {
        return $this->belongsTo(Publisher::class, 'publisher_id');
    }

    public function authors()
    {
        return $this->belongsTo(Author::class, 'author_id');
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Models\Author;
use App\Models\Book;
use App\Models\Category;
use App\Models\Publisher;
use Illuminate\Http\Request;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        $publishers = Publisher::all();
        $authors = Author::all();
        $books = Book::latest()->paginate(5);
        return view('dashboard.book.index', compact('books', 'categories', 'publishers', 'authors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $publishers = Publisher::all();
        $authors = Author::all();
        return view('dashboard.book.create', compact('authors', 'categories', 'publishers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'title' => 'required',
            'author' => 'required',
            'publisher' => 'required',
            'category' => 'required',
            'cover' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        $coverName = time() . '.' . $request->cover->extension();

        $request->cover->move(public_path('images'), $coverName);


        $Book = Book::create([
            'title'       => $request->input('title'),
            'author_id'       => $request->input('author'),
            'publisher_id'       => $request->input('publisher'),
            'category_id'       => $request->input('category'),
            'date_of_issue'       => $request->input('date_of_issue'),
            'description'       => $request->input('description'),
            'cover'       =>  $coverName,
        ]);


        $Book->save();

        return redirect()->route('book.index')
            ->with('success', 'Publisher created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($title)
    {
        $categories = Category::all();
        $book = Book::where('title', $title)->first();;
        $publishers = Publisher::all();
        $authors = Author::all();
        return view('dashboard.book.show', compact('book', 'authors', 'categories', 'publishers'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        $categories = Category::all();
        $publishers = Publisher::all();
        $authors = Author::all();
        return view('dashboard.book.edit', compact('book', 'authors', 'categories', 'publishers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        request()->validate([
            'title' => 'required',
            'author' => 'required',
            'publisher' => 'required',
            'category' => 'required',
            'cover' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        $input = $request->all();

        if ($image = $request->cover) {
            $coverName = time() . '.' . $image->extension();
            $image->move(public_path('images'), $coverName);
            $input['cover'] = "$coverName";
        } else {
            unset($input['cover']);
        }

        $book->update($input);



        return redirect()->route('book.index')
            ->with('success', 'Book created successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        $book->delete();

        return redirect()->route('book.index')
            ->with('success', 'Book deleted successfully');
    }
}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Http\Requests\StoreBookRequest;
use App\Http\Requests\UpdateBookRequest;

class BooksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('books.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreBookRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBookRequest $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateBookRequest  $request
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBookRequest $request, Book $book)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        //
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::latest()->paginate(5);
        return view('dashboard.index', compact('books'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dashboard/book/create.blade.php
@extends('layouts.dashboardApp')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h5>Add New Book</h5>
        </div>
        <hr>
        <div class="pull-right mb-3">
            <a class="btn btn-primary" href="{{ route('book.index') }}"> Back</a>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <div class="card-title"></div>

        @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif

        <form action="{{ route('book.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="mb-3">
                <label for="bookTitle" class="form-label">Title</label>
                <input type="text" name="title" class="form-control" id="bookTitle" placeholder="Title  ">
            </div>

            <div class="mb-3">
                <label for="bookCategory" class="form-label">Cover</label>
                <input type="file" name="cover" class="form-control">
            </div>

            <div class="mb-3">
                <label for="bookCategory" class="form-label">Description</label>
                <textarea class="form-control" id="editor" placeholder="Enter the Description"
                    name="description"></textarea>
            </div>

            <div class="mb-3">
                <label for="bookAuthor" class="form-label">Author</label>
                <select name="author" class="form-select" size="3" aria-label="size 3 select example">

                    @foreach ($authors as $author)

                    <option value="{{ $author->id }}">{{ $author->name }}</option>

                    @endforeach
                </select>
            </div>

            <div class="mb-3">
                <label for="bookAuthor" class="form-label">Publisher</label>
                <select name="publisher" class="form-select" size="3" aria-label="size 3 select example">

                    @foreach ($publishers as $publisher)

                    <option value="{{ $publisher->id }}">{{ $publisher->name }}</option>

                    @endforeach
                </select>
            </div>

            <div class="mb-3">
                <label for="bookAuthor" class="form-label">Category</label>
                <select name="category" class="form-select" size="3" aria-label="size 3 select example">

                    @foreach ($categories as $category)

                    <option value="{{ $category->id }}">{{ $category->name }}</option>

                    @endforeach
                </select>
            </div>

            <div class="mb-3">
                <label for="bookRelease" class="form-label">Release Date</label>
                <input type="date" name="date_of_issue" class="form-control" id="bookRelease" placeholder="Category">
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

    </div>
</div>

@endsection

resources/views/dashboard/book/edit.blade.php
@extends('layouts.dashboardApp')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h5>Add New Category</h5>
        </div>
        <hr>
        <div class="pull-right mb-3">
            <a class="btn btn-primary" href="{{ route('book.index') }}"> Back</a>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <div class="card-title"></div>

        @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif

        <form action="{{ route('book.update',$book->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="mb-3">
                <label for="bookTitle" class="form-label">Title</label>
                <input type="text" value="{{ $book->title }}" name="title" class="form-control" id="bookTitle"
                    placeholder="Title">
            </div>

            <img class="round-3 mb-3" src="{{ asset('images/'.$book->cover) }}" width="200px">

            <div class="mb-3">
                <label for="bookCategory" class="form-label">Cover</label>
                <input type="file" name="cover" class="form-control">
            </div>

            <div class="mb-3">
                <label for="bookCategory" class="form-label">Description</label>
                <textarea class="form-control" id="editor" placeholder="Enter the Description" name="description">
                {!! $book->description !!}</textarea>
            </div>

            <div class="mb-3">
                <label for="bookAuthor" class="form-label">Author</label>
                <select name="author" class="form-select" size="3" aria-label="size 3 select example">
                    @foreach($authors as $author)
                    <option value="{{ $author->id }}" {{$book->authors->id == $author->id ? 'selected' : ''}}>{{
                        $author->name}}</option>
                    @endforeach
                </select>
            </div>

            <div class="mb-3">
                <label for="bookAuthor" class="form-label">Publisher</label>
                <select name="publisher" class="form-select" size="3" aria-label="size 3 select example">

                    @foreach ($publishers as $publisher)

                    <option value="{{ $publisher->id }}" {{$book->publishers->id == $publisher->id ? 'selected' :
                        ''}}>{{
                        $publisher->name }}</option>

                    @endforeach
                </select>
            </div>

            <div class="mb-3">
                <label for="bookAuthor" class="form-label">Category</label>
                <select name="category" class="form-select" size="3" aria-label="size 3 select example">

                    @foreach ($categories as $category)

                    <option value="{{ $category->id }}" {{$book->categories->id == $category->id ? 'selected' : ''}}>{{
                        $category->name }}</option>

                    @endforeach
                </select>
            </div>

            <div class=" mb-3">
                <label for="bookRelease" class="form-label">Release Date</label>
                <input value="{{ $book->date_of_issue }}" type="date" name="date_of_issue" class="form-control"
                    id="bookRelease" placeholder="Category">
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

    </div>
</div>

@endsection

resources/views/dashboard/book/index.blade.php
@extends('layouts.dashboardApp')

@section('content')

<div class="row">
    <div class="col-md-12 mb-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem temporibus optio necessitatibus
                    quisquam itaque consequatur beatae praesentium voluptatem maiores. Laboriosam ducimus minus
                    accusamus laudantium? Facere animi perspiciatis inventore suscipit enim.</p>

                @can('category-create')
                <a class="btn btn-primary" href="{{ route('book.create') }}"> Create New Book</a>
                @endcan
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
                @endif
                <table class="table mt-0">
                    <tr>
                        <th>No</th>
                        <th>Cover</th>
                        <th>Title</th>
                        <th>Publisher</th>
                        <th>Author</th>
                        <th>Date Release</th>
                        <th>Options</th>
                    </tr>
                    @foreach ($books as $book)

                    <img src="{{ $book->cover }}" alt="" srcset="">
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>
                            <img src="{{ asset('images/'.$book->cover) }}" style="
                            width: 80px;
                            border-radius: 8px;
                            min-height: 120px;
                            object-fit: cover;" alt="" srcset="">
                        </td>
                        <td>
                            <h6>{{ $book->title }}</h6>
                            <p class="text-muted">{{ $book->categories->name }}</p>
                            <a class="text-decoration-none" href="{{ route('book.edit',$book->id) }}">Edit</a> - <a
                                class="text-decoration-none" href="{{ route('book.show',$book->title) }}">More</a>
                        </td>
                        <td>{{ $book->publishers->name }}</td>
                        <td>{{ $book->authors->name }}</td>
                        <td>{{ $book->date_of_issue }}</td>
                        <td>
                            <form action="{{ route('book.destroy',$book->id) }}" method="POST">

                                {{-- @can('category-edit')
                                <a class="btn btn-primary" href="{{ route('category.edit',$book->id) }}">Edit</a>
                                @endcan --}}

                                @csrf
                                @method('DELETE')
                                @can('category-delete')
                                <button type="submit" class="btn btn-danger">Delete</button>
                                @endcan
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </table>


                {!! $books->links() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/book/show.blade.php
@extends('layouts.dashboardApp')


@section('content')
<a class="btn btn-primary mb-3" href="{{ route('book.index') }}"> Back</a>
<div class="row">
    <div class="col">
        <h5 class="mb-3">{{ $book->title }}</h5>
    </div>
    <div class="col ">
        <a class="float-end text-decoration-none" href="">Edit</a>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <img class="img-fluid" src="{{ asset('images/'.$book->cover) }}" style="
                                            width: 225px;
                                            border-radius: 8px;
                                            height: 315px;
                                            object-fit: cover;" alt="{{ $book->title }}" srcset="">
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="card">
            <div class="card-body">
                <div class="card-title"></div>
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab"
                            data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home"
                            aria-selected="true">Details</button>
                        <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile"
                            type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Profile</button>
                        <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact"
                            type="button" role="tab" aria-controls="nav-contact" aria-selected="false">Contact</button>
                    </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">

                        <section class="my-3">

                            <dl>
                                <dt>Information</dt>
                                <dd>Title : {{ $book->title }}</dd>
                                <dd>Category : {{ $book->categories->name }}</dd>
                                <dd>Author : {{ $book->authors->name }}</dd>
                                <dd>Publisher : {{ $book->publishers->name }}</dd>
                                <dd>Release Date : {{ $book->date_of_issue }}</dd>

                                <dt>Description</dt>
                                <dd>{!! $book->description !!}</dd>
                            </dl>



                        </section>

                    </div>
                    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">...
                    </div>
                    <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">...
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@endsection