routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


//Users

use App\Http\Controllers\BooksController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\AuthorsController;
use App\Http\Controllers\PublishersController;


//Dashboard
use App\Http\Controllers\BookController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AuthorController;
use App\Http\Controllers\PublisherController;



use App\Http\Controllers\CategoryController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('books', BooksController::class);
Route::resource('categories', CategoriesController::class);
Route::resource('authors', AuthorsController::class);
Route::resource('publishers', PublishersController::class);

Route::group(['middleware' => ['auth']], function () {

    Route::prefix('dashboard')->group(function () {
        //admin pages

        Route::get('/', [App\Http\Controllers\DashboardController::class, 'index'])->name('Dashboard');
        Route::get('book/{title}', ['as' => 'book.show', 'uses' =>   'BookController@show']);
        Route::resource('book', BookController::class);
        Route::resource('author', AuthorController::class);
        Route::resource('publisher', PublisherController::class);

        Route::resource('roles', RoleController::class);
        Route::resource('category', CategoryController::class);
        Route::resource('users', UserController::class);
    });
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>



    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <link href="{{ asset('bootstrap/css/blog.css') }}" rel="stylesheet">


    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{{ asset('bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">

        @include('layouts.navigation')

        <main class="py-3">
            @yield('content')
        </main>
        <footer class="blog-footer mt-auto py-3">
            <p>
                <a href="#">CopyRight</a>
            </p>
        </footer>
    </div>


</body>

</html>

resources/views/layouts/dashboardApp.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <link rel="stylesheet" href="{{ asset('https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css') }}">


    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="{{ asset('https://fonts.googleapis.com/css?family=Nunito') }}" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{{ asset('bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ asset('bootstrap/css/dashboard.css') }}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{{ asset('bootstrap/css/dashboard.css') }}" rel="stylesheet">

</head>

<body>
    <div id="app">

        @include('layouts.dashboardNavigation')

        <div class="container-fluid">
            <div class="row mt-4">
                @include('layouts.sidebar')

                <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                    @yield('content')
                </main>
            </div>
        </div>
    </div>

    <script src="{{ asset('ckeditor5-build-classic/ckeditor.js') }}"></script>

    <script>
        ClassicEditor
                    .create( document.querySelector( '#editor' ) )
                    .catch( error => {
                        console.error( error );
                    } );
    </script>


    <script src="{{ asset('bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>

    <script src="{{ asset('https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js') }}"
        integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous">
    </script>

    <script src="{{ asset('bootstrap/js/dashboard.js') }}"></script>

</body>

</html>

resources/views/layouts/dashboardNavigation.blade.php
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">myBook</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
        data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-nav form-control form-control-dark py-0">
        <div class="nav-item text-nowrap">
            <a class="nav-link px-3" href="{{ route('logout') }}" onclick="event.preventDefault();
                                            document.getElementById('logout-form').submit();">Sign out</a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>
        </div>
    </div>
</header>

resources/views/layouts/navigation.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-white border">
    <div class="container">
        <a class="navbar-brand fs-4 fw-bold text-info" href="{{ route('home') }}">
            myBook
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav me-auto">

                <li class="nav-item {{ request()->is('/') ? 'active' : '' }}">
                    <a class="nav-link" href="/">Home</a>
                </li>

                <li class="nav-item {{ Route::is('books.index*') ? 'fw-bold' : '' }}">
                    <a class="nav-link" href="{{ route('books.index') }}">Books</a>
                </li>

                <li class="nav-item {{ Route::is('categories.index*') ? 'fw-bold' : '' }}">
                    <a class="nav-link" href="{{ route('categories.index') }}">Categories</a>
                </li>

                <li class="nav-item {{ Route::is('authors.index*') ? 'fw-bold' : '' }}">
                    <a class="nav-link" href="{{ route('authors.index') }}">Authors</a>
                </li>

                <li class="nav-item {{ Route::is('publishers.index*') ? 'fw-bold' : '' }}">
                    <a class="nav-link" href="{{ route('publishers.index') }}">Publishers</a>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ms-auto">
                <!-- Authentication Links -->
                @guest
                @if (Route::has('login'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                </li>
                @endif

                @if (Route::has('register'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                </li>
                @endif
                @else
                <li class="nav-item">
                    <a class="nav-link" href="/dashboard">{{ __('Dashboard') }}</a>
                </li>
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }}
                    </a>

                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                    </div>
                </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/sidebar.blade.php
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3">
        <ul class="nav flex-column">
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span>Administrator</span>

            </h6>
            <li class="nav-item ">
                <a class="nav-link {{ request()->is('dashboard') ? 'active' : '' }}" aria-current="page"
                    href="/dashboard">
                    <i class="bi bi-house-door-fill me-2"></i>
                    Dashboard
                </a>
            </li>

            <li class="nav-item ">
                <a class="nav-link {{ request()->routeIs('roles.*') ? 'active' : '' }}" aria-current=" page"
                    href="{{ route('roles.index') }}">
                    <i class="bi bi-toggle-on me-2"></i>
                    Roles
                </a>
            </li>

            <li class="nav-item ">
                <a class="nav-link {{ request()->routeIs('users.*') ? 'active' : '' }}" aria-current=" page"
                    href="{{ route('users.index') }}">
                    <i class="bi bi-people-fill me-2"></i>
                    Users
                </a>
            </li>



        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Operations</span>

        </h6>
        <ul class="nav flex-column mb-2">

            <li class="nav-item ">
                <a class="nav-link {{ request()->routeIs('book.*') ? 'active' : '' }}" aria-current=" page"
                    href="{{ route('book.index') }}">
                    <i class="bi bi-book-fill me-2"></i>
                    Book
                </a>
            </li>

            <li class="nav-item ">
                <a class="nav-link {{ request()->routeIs('category.*') ? 'active' : '' }}" aria-current=" page"
                    href="{{ route('category.index') }}">
                    <i class="bi bi-tags-fill me-2"></i>
                    Category
                </a>
            </li>

            <li class="nav-item ">
                <a class="nav-link {{ request()->routeIs('author.*') ? 'active' : '' }}" aria-current=" page"
                    href="{{ route('author.index') }}">
                    <i class="bi bi-person-workspace me-2"></i>
                    Author
                </a>
            </li>

            <li class="nav-item ">
                <a class="nav-link {{ request()->routeIs('publisher.*') ? 'active' : '' }}" aria-current=" page"
                    href="{{ route('publisher.index') }}">
                    <i class="bi bi-person-lines-fill me-2"></i>
                    Publisher
                </a>
            </li>
        </ul>
    </div>
</nav>